GRANT SUPER, PROCESS ON *.* TO 'cacticactiserver'@'%' IDENTIFIED BY "Cclt_504";
SHOW /*!50002 GLOBAL */ STATUS;
SHOW VARIABLES;
SHOW ENGINES;
SHOW SLAVE STATUS;
SHOW MASTER LOGS;
SHOW PROCESSLIST;
SHOW /*!50000 ENGINE*/ INNODB STATUS;
